### ISSUE TITLE
After Elemntor updates 3.1.1 no website content is visible 

### ISSUE THREAD

**Issue by orelmeister** [droitlab/droit-elementor-addons-troubleshoot#1]
After Elemntor updates 3.1.1 no website content is visible

**Comment by droitlab** [comment]
Hi,
This is happening for the latest update on Elementor, it's not by our addon. Anyway you can easily fix this. Please:

1. Go to "Elements" tab in Droit Elementor Addons.
2. Then enable all the widgets or the widgets you have used.
3. If they are already enabled, please disable and then re-enable them.
4. Finally, hit "Save Settings". 

Thanks.
![Enable_addons_again](https://user-images.githubusercontent.com/10178198/106592336-96c6ef00-6579-11eb-8f81-bce97ff852d1.png)
